# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso', models.CharField(max_length=120, verbose_name='Frase')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Aviso',
            },
        ),
        migrations.CreateModel(
            name='Dica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dica', models.CharField(max_length=120, verbose_name='Frase')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Dica',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=120, verbose_name='Frase')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cumuruxatiba/images')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='Descrição')),
                ('link', models.CharField(blank=True, max_length=120, verbose_name='link')),
                ('palavralink', models.CharField(blank=True, max_length=120, verbose_name='palavra-link')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Legenda')),
                ('content', models.TextField(blank=True, verbose_name='Conteudo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Home',
            },
        ),
    ]
